name: Lint and Test

on: [push,pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1 # Not needed with a .ruby-version file
      - name: Install dependencies
        run: make install
      - name: Run linter
        run: bundle exec rake rubocop
      - name: Run test
        run: make test